apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wad23-poi-backend-app-dev
  annotations:
    argocd/app-name: wad23-poi-backend-app-dev
    backstage.io/kubernetes-id: wad23-poi-backend-app
    backstage.io/kubernetes-namespace: wad23
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devhub-test/wad23-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.redhatdevhub.l07n.p1.openshiftapps.com/dev-pipelines/ns/wad23/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.redhatdevhub.l07n.p1.openshiftapps.com/k8s/ns/wad23/deployments/wad23-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.redhatdevhub.l07n.p1.openshiftapps.com/#https://github.com/devhub-test/wad23-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-wad23
  providesApis:
    - backend-api-wad23
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-wad23
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-wad23
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://wad23-poi-backend-app-wad23.apps.redhatdevhub.l07n.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/devhub-test/wad23-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-wad23
  definition:
    $text: https://github.com/devhub-test/wad23-backend/tree/main/src/main/resources/META-INF/openapi.yaml
